name: Continuous Integration
on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Build project
        run: sbt test
