name: Continuous Integration
on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Build project
        run: sbt test

  scalafmt:
    name: Scalafmt
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch (fast)
        uses: actions/checkout@v3.0.2
      - name: Scalafmt
        run: sbt scalafmtCheckAll
