name: Continuous Integration
on:
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Setup JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: 8
          cache: sbt
      - name: Build and Test
        run: sbt -v +test
