name: release
on:
  push:
    branches: [master, main]
    tags: ["*"]

env:
  PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
  PGP_SECRET: ${{ secrets.PGP_SECRET }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v14
      - run: sbt ci-release
